CITY_SENEGAL = [
    ('Dakar', 'Dakar'),
    ('Aéroport AIBD', 'Aéroport AIBD'),
    ('Diamniadio', 'Diamniadio'),
    ('Guédiawaye', 'Guédiawaye'),
    ('Pikine', 'Pikine'),
    ('Centre Cutlure de Diamniadio', 'Centre Cutlure de Diamniadio'),
    ('Thiaroye', 'Thiaroye'),
    ('Yeumbeul', 'Yeumbeul'),
    ('Port Autonome de Dakar', 'Port Autonome de Dakar'),
    ('Palais de Justice', 'Palais de Justice'),
    ('Colobane', 'Colobane'),
    ('Petersen', 'Petersen'),
    ('Liberté 5', 'Liberté 5'),
    ('Liberté 6', 'Liberté 6'),
    ('Almadies', 'Almadies'),
    ('Mermoz', 'Mermoz'),
    ('Ouakam', 'Ouakam'),
    ('Ngor', 'Ngor'),
    ('Yoff', 'Yoff'),
    ('Fann', 'Fann'),
    ('Point E', 'Point E'),
    ('Médina', 'Médina'),
    ('Fass', 'Fass'),
    ('Hann', 'Hann'),
    ('Grand Yoff', 'Grand Yoff'),
    ('Parcelles Assainies', 'Parcelles Assainies'),
    ('Keur Massar', 'Keur Massar'),
    ('Malika', 'Malika'),
    ('Lac Rose', 'Lac Rose'),
    ('Sicap Liberté', 'Sicap Liberté'),
    ('Sicap Amitié', 'Sicap Amitié'),
    ('Sicap Baobab', 'Sicap Baobab'),
    ('Sicap Sacré Coeur', 'Sicap Sacré Coeur'),
    ('Sicap Karack', 'Sicap Karack'),
    ('Sicap Mbao', 'Sicap Mbao'),
    ('Sicap Mermoz', 'Sicap Mermoz'),
    ('Sicap Rue 10', 'Sicap Rue 10'),
    ('Sandaga', 'Sandaga'),
    ('Plateau', 'Plateau'),
    ('Nord Foire', 'Nord Foire'),
    ('HLM', 'HLM'),
    ('Médina Gounass', 'Médina Gounass'),
    ('Médina Coura', 'Médina Coura'),
    ('Castor', 'Castor'),
    ('Grand Dakar', 'Grand Dakar'),
    ('Dieuppeul', 'Dieuppeul'),
    ('Derklé', 'Derklé'),
    ('Thies', 'Thies'),
    ('Kaolack', 'Kaolack'),
    ('Saint-Louis', 'Saint-Louis'),
    ('Touba', 'Touba'),
    ('Ziguinchor', 'Ziguinchor'),
    ('Louga', 'Louga'),
    ('Richard-Toll', 'Richard-Toll'),
    ('Tambacounda', 'Tambacounda'),
    ('Kolda', 'Kolda'),
    ('Mbacké', 'Mbacké'),
    ('Fatick', 'Fatick'),
    ('Diourbel', 'Diourbel'),
    ('Kaffrine', 'Kaffrine'),
    ('Kédougou', 'Kédougou'),
    ('Sédhiou', 'Sédhiou'),
    ('Bignona', 'Bignona'),
    ('Matam', 'Matam'),
    ('Kanel', 'Kanel'),
    ('Goudomp', 'Goudomp'),
    ('Vélingara', 'Vélingara'),
    ('Sokone', 'Sokone'),
    ('Koumpentoum', 'Koumpentoum'),
    ('Mékhé', 'Mékhé'),
    ('Nioro du Rip', 'Nioro du Rip'),
    ('Ourossogui', 'Ourossogui'),
    ('Pikine', 'Pikine'),
    ('Rufisque', 'Rufisque'),
    ('Guinguinéo', 'Guinguinéo'),
    ('Koungheul', 'Koungheul'),
    ('Mbour', 'Mbour'),
    ('Diourbel', 'Diourbel'),
    ('Tivaouane', 'Tivaouane'),
    ('Ben Tally', 'Ben Tally'),
    ('Bargny', 'Bargny'),
    ('Bambilor', 'Bambilor'),
    ('Ben Baraque', 'Ben Baraque'),
    ('Sangalkam', 'Sangalkam'),
    ('Keur Massar', 'Keur Massar'),
    ('Keur Ndiaye Lo', 'Keur Ndiaye Lo'),
    ('Kounoune', 'Kounoune')
]

# Trier la liste par ordre alphabétique
CITY_SENEGAL.sort(key=lambda x: x[0])

# Supprimer les doublons en utilisant un ensemble (set)
CITY_SENEGAL = list(set(CITY_SENEGAL))

# Retrier la liste après avoir supprimé les doublons
CITY_SENEGAL.sort(key=lambda x: x[0])
